version: '3.4'

services:
  catalog.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identity.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

